AWSTemplateFormatVersion: ''
Description: ''
Transform: ''
Rules:
  ProdCheck:
    RuleCondition: ''
    Assertions:
      - '[Assert={"Fn::Contains":[["prod","stg"],{"Ref":"EnvType"}]}]': ''
        Assert: ''
        AssertDescription: ''
Resources:
  FunctionTester:
    Type: ''
    Properties:
      Base64Val: ''
  EC2Instance:
    Type: ''
    CreationPolicy:
      ResourceSignal:
        Timeout: ''
    Properties:
      ImageId: ''
      InstanceType: ''
      JoinVal: ''
      SplitVal: ''
      SelectVal: ''
      CidrVal: ''
      AzsVal: ''
      MapVal: ''
      ImportVal: ''
      JsonVal: ''
      LengthVal: ''
  Fn::ForEach::Loop:
    - '[Identifier]': ''
    - '0': ''
      '1': ''
      '[0=A]': ''
    - '[Resource${Identifier}]':
        Type: AWS::SNS::Topic
        Properties:
          TopicName:
            '!Sub': Topic-${Identifier}
      Resource${Identifier}:
        Type: ''
        Properties:
          TopicName: ''
