lang: ja
index:
  output: sample/output/index.html
  title: YamlDocDock サンプル

pages:
  - title: Sample Documentation
    sources:
      - sample/sources/ecs.yml
      - sample/sources/ec2.yml
    guideDir: guides
    aliasDir: aliases
    output: sample/output/ecs-and-ec2.html

  - title: Sample Cfn Documentation
    mode: cfn
    sources:
      - sample/sources/cfn_main.yml
      - sample/sources/cfn_part.yml
    guideDir: guides
    aliasDir: aliases
    output: sample/output/cfn.html